name: sidebar_with_animation
description: Animated collapsible smooth sidebar with full control to customize it for your own designs for Flutter apps
version: 0.1.3
homepage: https://github.com/mokhselim/animated_side_bar.git
repository: https://github.com/mokhselim/animated_side_bar.git

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# This package supports all platforms listed below.
platforms:
  linux:
  macos:
  web:
  windows:

topics:
  - widget
  - ui
  - drawer
  - navigation
  - sidebar